#  ====================== Operador ==   ======================

#c = 5 == 5  #5 igual a 5 es True
#print(c)

# c = "Seba" == "sebin"
# print(c)
# 
# d = "seba" == "Seba"
# print(d)
# 
# e = 5 == 5.0
# print(e)



# =========== Operador Diferente que !=  ===================

# a = 5 != 3
# b = "seba" != "seba"
# 
# print(a)
# print(b)

# =========== Operador menor que < =========================

b = 5 < 3
print(b)

# =========== Operador mayor que > =========================
c = 5 > 3
print(c)

# =========== Operador menor igual que <= =========================

d = 3 <= 3
print (d)

# =========== Operador mayor igual que < =========================

e = 10 >= 9
print (e)